#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str, T: str):
    S = sorted(list(S))
    T = sorted(list(T))
    atcoder = ('a', 't', 'c', 'o', 'd', 'e', 'r')
    for i in range(len(S)):
        if S[i] == T[i] or \
        S[i] == '@' and T[i] != '@' and T[i] in atcoder or \
        S[i] != '@' and T[i] == '@' and S[i] in atcoder:
            continue
        else:
            print(NO)
            return 
    print(YES)
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)

if __name__ == '__main__':
    main()
