#!/usr/bin/env python3
import sys


def solve(S: str):
    S = list(S)
    ans = []
    for i in range(0, len(S), 2):
        ans.append(S[i+1])
        ans.append(S[i])
    print("".join(ans))
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word

    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)


if __name__ == "__main__":
    main()
