#!/usr/bin/env python3

MOD = 998244353  # type: int


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    # Failed to predict input format
    pass

if __name__ == '__main__':
    main()
